export const matchRows = [
  { key: "M4",  dateKey: "jun12", badge: "#1D428A", group: "Group D",       teams: ["🇺🇸", "USA",         "Paraguay",    "🇵🇾"], date: "June 12", sub: "Friday · 6:00 pm PT" },
  { key: "M15", dateKey: "jun15", badge: "#239F40", group: "Group G",       teams: ["🇮🇷", "IR Iran",     "New Zealand", "🇳🇿"], date: "June 15", sub: "Monday · 6:00 pm PT" },
  { key: "M26", dateKey: "jun18", badge: "#C8102E", group: "Group B",       teams: ["🇨🇭", "Switzerland", "Bosnia and Herzegovina", "🇧🇦"], date: "June 18", sub: "Thursday · 12:00 pm PT" },
  { key: "M39", dateKey: "jun21", badge: "#C49A00", group: "Group G",       teams: ["🇧🇪", "Belgium",     "IR Iran",     "🇮🇷"], date: "June 21", sub: "Sunday · 12:00 pm PT" },
  { key: "M59", dateKey: "jun25", badge: "#E30A17", group: "Group D",       teams: ["🇹🇷", "Türkiye",      "USA",         "🇺🇸"], date: "June 25", sub: "Thursday · 7:00 pm PT" },
  { key: "M73", dateKey: "jun28", badge: "#5C4033", group: "Round of 32",   teams: ["",   "TBD",          "TBD",         ""],   date: "June 28", sub: "Sunday · 12:00 pm PT",    homeTbd: true, awayTbd: true },
  { key: "M84", dateKey: "jul2",  badge: "#37474F", group: "Round of 32",   teams: ["",   "TBD",          "TBD",         ""],   date: "July 2",  sub: "Thursday · 12:00 pm PT",  homeTbd: true, awayTbd: true },
  { key: "M98", dateKey: "jul10", badge: "#1A1A2E", group: "Quarter-Final", teams: ["",   "TBD",          "TBD",         ""],   date: "July 10", sub: "Friday · 12:00 pm PT",    homeTbd: true, awayTbd: true },
];

export const matchMeta = {
  M4: {
    home: { flag: "🇺🇸", name: "USA", country: "United States" },
    away: { flag: "🇵🇾", name: "PAR", country: "Paraguay" },
    highlight: "USMNT opens the World Cup on home soil against Paraguay in a pivotal Group D clash.",
    h2h: { total: 5, team1wins: 3, draws: 1 },
    story: {
      title: "A Battle of Style and Spirit",
      desc: "The stars and stripes take on Paraguay in a clash of ambition and resilience. Expect intensity, tactical chess, and moments that define a tournament.",
      bullets: ["USA back home with a point to prove", "Paraguay's defense, a true wall", "Midfield control could decide it all"],
    },
    stats: {
      home: { winRate: 68, goalsPerGame: 2.1, form: ["W","W","D","W","L"], goalsConceded: 1.8 },
      away: { winRate: 52, goalsPerGame: 1.3, form: ["L","W","D","L","W"], goalsConceded: 1.2 },
      allTime: { homeGoals: 7, awayGoals: 4, homePoss: 52, awayPoss: 48, homePass: 85, awayPass: 82 },
      lastMeeting: { date: "June 2, 2021", type: "Friendly", homeScore: 2, awayScore: 1 },
    },
    stars: [
      { name: "Christian Pulisic",  flag: "🇺🇸", team: "USA",      pos: "Forward",    club: "AC Milan",         img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg/330px-Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg" },
      { name: "Weston McKennie",    flag: "🇺🇸", team: "USA",      pos: "Midfielder", club: "Juventus",         img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Weston_McKennie_USMNT_v_Belgium_Mar_28_2026-68_%28cropped%29.jpg/330px-Weston_McKennie_USMNT_v_Belgium_Mar_28_2026-68_%28cropped%29.jpg" },
      { name: "Gio Reyna",          flag: "🇺🇸", team: "USA",      pos: "Midfielder", club: "Borussia Dortmund", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Gio_Reyna_USMNT_v_Belgium_Mar_28_2026-60_%28cropped%29.jpg/330px-Gio_Reyna_USMNT_v_Belgium_Mar_28_2026-60_%28cropped%29.jpg" },
      { name: "Tyler Adams",        flag: "🇺🇸", team: "USA",      pos: "Midfielder", club: "Bournemouth",      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/2021-11-06_Fu%C3%9Fball%2C_M%C3%A4nner%2C_1._Bundesliga%2C_RB_Leipzig_-_Borussia_Dortmund_1DX_1527_by_Stepro_%28cropped2%29.jpg/330px-2021-11-06_Fu%C3%9Fball%2C_M%C3%A4nner%2C_1._Bundesliga%2C_RB_Leipzig_-_Borussia_Dortmund_1DX_1527_by_Stepro_%28cropped2%29.jpg" },
      { name: "Miguel Almirón",     flag: "🇵🇾", team: "Paraguay", pos: "Midfielder", club: "Newcastle United", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Miguel_Almir%C3%B3n_Red_Bull_Atlanta_5.31.25-069_%28cropped%29.jpg/330px-Miguel_Almir%C3%B3n_Red_Bull_Atlanta_5.31.25-069_%28cropped%29.jpg" },
      { name: "Gustavo Gómez",      flag: "🇵🇾", team: "Paraguay", pos: "Defender",   club: "Palmeiras",        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Gustavo-Gomez-Palmeiras-Athletico-jul-2022-2.jpg/330px-Gustavo-Gomez-Palmeiras-Athletico-jul-2022-2.jpg" },
      { name: "Julio Enciso",       flag: "🇵🇾", team: "Paraguay", pos: "Forward",    club: "Brighton",         img: "https://upload.wikimedia.org/wikipedia/commons/4/40/Enciso_2022.jpg" },
    ],
  },
  M15: {
    home: { flag: "🇮🇷", name: "IRI", country: "Iran" },
    away: { flag: "🇳🇿", name: "NZL", country: "New Zealand" },
    highlight: "Iran face New Zealand in a decisive Group G encounter at SoFi Stadium.",
    h2h: { total: 2, team1wins: 1, draws: 0 },
    story: {
      title: "The Eagle Meets the All Whites",
      desc: "Iran bring Asian football's fire to SoFi Stadium in a clash against New Zealand's determined All Whites. Tactical discipline versus South Pacific grit.",
      bullets: ["Iran's physical press tested at the highest level", "New Zealand looking to cause a major upset", "Set pieces could swing the result"],
    },
    stats: {
      home: { winRate: 55, goalsPerGame: 1.6, form: ["W","D","W","W","L"], goalsConceded: 1.4 },
      away: { winRate: 38, goalsPerGame: 0.9, form: ["L","D","L","W","L"], goalsConceded: 1.9 },
      allTime: { homeGoals: 4, awayGoals: 1, homePoss: 54, awayPoss: 46, homePass: 79, awayPass: 71 },
      lastMeeting: { date: "Nov 14, 2017", type: "WC Qualifier", homeScore: 2, awayScore: 0 },
    },
    stars: [
      { name: "Mehdi Taremi",          flag: "🇮🇷", team: "Iran",        pos: "Forward",    club: "Inter Milan",       img: "https://upload.wikimedia.org/wikipedia/commons/7/74/Iran_-_Japan%2C_AFC_Asian_Cup_2019_42_%28cropped%29.jpg" },
      { name: "Sardar Azmoun",         flag: "🇮🇷", team: "Iran",        pos: "Forward",    club: "Roma",              img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Sardar_Azmoun_-_IRN_vs_USA_-_FIFA_WC_2022.jpg/330px-Sardar_Azmoun_-_IRN_vs_USA_-_FIFA_WC_2022.jpg" },
      { name: "Alireza Jahanbakhsh",   flag: "🇮🇷", team: "Iran",        pos: "Midfielder", club: "Feyenoord",         img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/2022_FIFA_World_Cup_England_6%E2%80%932_Iran_-_%2826%29_%28cropped%29.jpg/330px-2022_FIFA_World_Cup_England_6%E2%80%932_Iran_-_%2826%29_%28cropped%29.jpg" },
      { name: "Chris Wood",            flag: "🇳🇿", team: "New Zealand", pos: "Forward",    club: "Nottingham Forest", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Chris_Wood_%28cropped%29.jpg/330px-Chris_Wood_%28cropped%29.jpg" },
      { name: "Elijah Just",           flag: "🇳🇿", team: "New Zealand", pos: "Midfielder", club: "Rapid Vienna" },
    ],
  },
  M26: {
    home: { flag: "🇨🇭", name: "SUI", country: "Switzerland" },
    away: { flag: "🇧🇦", name: "BIH", country: "Bosnia and Herzegovina" },
    highlight: "Switzerland take on Bosnia and Herzegovina in a must-watch Group B battle at SoFi Stadium.",
    h2h: { total: 3, team1wins: 2, draws: 1 },
    story: {
      title: "Alpine Precision vs Balkan Spirit",
      desc: "Switzerland's meticulous, disciplined style collides with Bosnia and Herzegovina's passionate, attack-minded football. A tactical battle with European pride on the line.",
      bullets: ["Switzerland's defensive solidity is world-class", "Bosnia carry the passion of a nation watching from home", "Midfield battle could define which side advances"],
    },
    stats: {
      home: { winRate: 62, goalsPerGame: 1.8, form: ["W","D","W","W","D"], goalsConceded: 1.1 },
      away: { winRate: 44, goalsPerGame: 1.5, form: ["W","L","D","W","L"], goalsConceded: 1.7 },
      allTime: { homeGoals: 5, awayGoals: 2, homePoss: 55, awayPoss: 45, homePass: 87, awayPass: 74 },
      lastMeeting: { date: "Oct 12, 2014", type: "Friendly", homeScore: 1, awayScore: 3 },
    },
    rankings: {
      home: null,
      away: { rank: 65, total_points: "1385.0", confederation: "UEFA" },
    },
    stars: [
      { name: "Granit Xhaka",    flag: "🇨🇭", team: "Switzerland",           pos: "Midfielder", club: "Bayer Leverkusen", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Granit_Xhaka_%28cropped%29.jpg/330px-Granit_Xhaka_%28cropped%29.jpg" },
      { name: "Yann Sommer",     flag: "🇨🇭", team: "Switzerland",           pos: "Goalkeeper", club: "Inter Milan",      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/FC_Salzburg_gegen_Inter_Mailand_%28Testspiel_2023-08-09%29_69.jpg/330px-FC_Salzburg_gegen_Inter_Mailand_%28Testspiel_2023-08-09%29_69.jpg" },
      { name: "Xherdan Shaqiri", flag: "🇨🇭", team: "Switzerland",           pos: "Midfielder", club: "Chicago Fire",     img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Xherdan_Shaqiri_2018.jpg/330px-Xherdan_Shaqiri_2018.jpg" },
      { name: "Edin Džeko",      flag: "🇧🇦", team: "Bosnia and Herzegovina", pos: "Forward",    club: "Fenerbahçe",      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg/330px-20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg" },
      { name: "Miralem Pjanić",  flag: "🇧🇦", team: "Bosnia and Herzegovina", pos: "Midfielder", club: "Sharjah FC",      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Miralem_Pjani%C4%87_2025.jpg/330px-Miralem_Pjani%C4%87_2025.jpg" },
    ],
  },
  M39: {
    home: { flag: "🇧🇪", name: "BEL", country: "Belgium" },
    away: { flag: "🇮🇷", name: "IRI", country: "Iran" },
    highlight: "Belgium face Iran in a critical Group G match that could determine which teams advance.",
    h2h: { total: 1, team1wins: 1, draws: 0 },
    story: {
      title: "Red Devils vs. Team Melli",
      desc: "Belgium's golden generation against Iran's disciplined and passionate squad. This Group G encounter could send shockwaves through the entire tournament bracket.",
      bullets: ["Belgium's attack is among the world's deadliest", "Iran's organized defense won't make it easy", "A must-win situation for both sides"],
    },
    stats: {
      home: { winRate: 72, goalsPerGame: 2.3, form: ["W","W","W","D","L"], goalsConceded: 1.3 },
      away: { winRate: 55, goalsPerGame: 1.6, form: ["W","D","W","W","L"], goalsConceded: 1.4 },
      allTime: { homeGoals: 2, awayGoals: 0, homePoss: 58, awayPoss: 42, homePass: 88, awayPass: 76 },
      lastMeeting: { date: "June 18, 2014", type: "World Cup", homeScore: 1, awayScore: 0 },
    },
    stars: [
      { name: "Kevin De Bruyne",  flag: "🇧🇪", team: "Belgium", pos: "Midfielder", club: "Manchester City", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/330px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg" },
      { name: "Romelu Lukaku",    flag: "🇧🇪", team: "Belgium", pos: "Forward",    club: "Roma",            img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Romelu_Lukaku_2021.jpg/330px-Romelu_Lukaku_2021.jpg" },
      { name: "Thibaut Courtois", flag: "🇧🇪", team: "Belgium", pos: "Goalkeeper", club: "Real Madrid",     img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Courtois_2018_%28cropped%29.jpg/330px-Courtois_2018_%28cropped%29.jpg" },
      { name: "Mehdi Taremi",     flag: "🇮🇷", team: "Iran",    pos: "Forward",    club: "Inter Milan",     img: "https://upload.wikimedia.org/wikipedia/commons/7/74/Iran_-_Japan%2C_AFC_Asian_Cup_2019_42_%28cropped%29.jpg" },
      { name: "Sardar Azmoun",    flag: "🇮🇷", team: "Iran",    pos: "Forward",    club: "Roma",            img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Sardar_Azmoun_-_IRN_vs_USA_-_FIFA_WC_2022.jpg/330px-Sardar_Azmoun_-_IRN_vs_USA_-_FIFA_WC_2022.jpg" },
    ],
  },
  M59: {
    home: { flag: "🇹🇷", name: "TUR", country: "Türkiye" },
    away: { flag: "🇺🇸", name: "USA", country: "United States" },
    highlight: "Türkiye face the USMNT in a high-stakes Group D clash at SoFi Stadium with qualification on the line.",
    h2h: { total: 4, team1wins: 2, draws: 1 },
    story: {
      title: "Crescent & Stars vs Stars & Stripes",
      desc: "Türkiye bring their trademark intensity and technical flair to meet the USMNT on American soil. SoFi Stadium will be electric — 70,000 fans on one side, a nation watching across the Atlantic.",
      bullets: ["Türkiye's attack is unpredictable and lethal on the break", "USA need a result to guarantee advancement", "This is SoFi at its loudest — expect an atmosphere like no other"],
    },
    stats: {
      home: { winRate: 58, goalsPerGame: 1.7, form: ["W","W","L","D","W"], goalsConceded: 1.5 },
      away: { winRate: 68, goalsPerGame: 2.1, form: ["W","W","D","W","L"], goalsConceded: 1.8 },
      allTime: { homeGoals: 6, awayGoals: 3, homePoss: 50, awayPoss: 50, homePass: 81, awayPass: 84 },
      lastMeeting: { date: "May 26, 2010", type: "Friendly", homeScore: 2, awayScore: 2 },
    },
    stars: [
      { name: "Hakan Çalhanoğlu", flag: "🇹🇷", team: "Türkiye", pos: "Midfielder", club: "Inter Milan", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/AUT_vs._TUR_2016-03-29_%28342%29.jpg/330px-AUT_vs._TUR_2016-03-29_%28342%29.jpg" },
      { name: "Arda Güler",       flag: "🇹🇷", team: "Türkiye", pos: "Midfielder", club: "Real Madrid", img: "https://upload.wikimedia.org/wikipedia/commons/2/26/Derbide_Fenerbah%C3%A7e_Yedek_Oyuncu_Arda_G%C3%BCler_%282021-22_S%C3%BCper_Lig_-_Cropped%29.jpg" },
      { name: "Kenan Yıldız",     flag: "🇹🇷", team: "Türkiye", pos: "Forward",    club: "Juventus",    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Kenan_Y%C4%B1ld%C4%B1z_in_the_international_match_%28March_2025%29_%28cropped%29.jpg/330px-Kenan_Y%C4%B1ld%C4%B1z_in_the_international_match_%28March_2025%29_%28cropped%29.jpg" },
      { name: "Christian Pulisic",flag: "🇺🇸", team: "USA",     pos: "Forward",    club: "AC Milan",    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg/330px-Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg" },
      { name: "Weston McKennie",  flag: "🇺🇸", team: "USA",     pos: "Midfielder", club: "Juventus",    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Weston_McKennie_USMNT_v_Belgium_Mar_28_2026-68_%28cropped%29.jpg/330px-Weston_McKennie_USMNT_v_Belgium_Mar_28_2026-68_%28cropped%29.jpg" },
    ],
  },
  M73: {
    home: { flag: "❓", name: "TBD", country: "To Be Determined" },
    away: { flag: "❓", name: "TBD", country: "To Be Determined" },
    highlight: "Round of 32 match — teams to be determined after group stage.",
    h2h: { total: 0, team1wins: 0, draws: 0 },
    story: {
      title: "The Last Dance Begins",
      desc: "The knockout stage arrives at SoFi Stadium. Two nations, one dream, and 90 minutes to settle it. The World Cup just got serious.",
      bullets: ["Knockout football: one mistake ends everything", "SoFi becomes the most electric venue in world football", "Champions are made in moments like these"],
    },
    stats: null,
  },
  M84: {
    home: { flag: "❓", name: "TBD", country: "To Be Determined" },
    away: { flag: "❓", name: "TBD", country: "To Be Determined" },
    highlight: "Round of 32 match — teams to be determined after group stage.",
    h2h: { total: 0, team1wins: 0, draws: 0 },
    story: {
      title: "One Match. One Dream.",
      desc: "Only 32 teams remain. The road to the World Cup Final narrows at SoFi Stadium as two nations meet in a battle that will define their tournaments.",
      bullets: ["Every touch, every decision — magnified", "The crowd brings an energy that lifts nations", "History is written in 90-minute chapters"],
    },
    stats: null,
  },
  M98: {
    home: { flag: "❓", name: "TBD", country: "To Be Determined" },
    away: { flag: "❓", name: "TBD", country: "To Be Determined" },
    highlight: "Quarter-Final — the road to the World Cup Final runs through SoFi Stadium.",
    h2h: { total: 0, team1wins: 0, draws: 0 },
    story: {
      title: "Glory Awaits at SoFi",
      desc: "The Quarter-Final stage. The last eight teams standing square off under the lights of SoFi Stadium. Win here and you are four steps from immortality.",
      bullets: ["The final eight — only the elite remain", "SoFi Stadium: where legends are born", "Semi-finals, and the dream, are on the line"],
    },
    stats: null,
  },
};
