const PLACE_URLS = {
  "the west hollywood edition": "https://www.editionhotels.com/weho/",
  "petit ermitage": "https://www.petitermitage.com/",
  "andaz west hollywood": "https://www.hyatt.com/andaz/laxss-andaz-west-hollywood",
  "best western plus sunset plaza": "https://www.bestwestern.com/",
  "ramada plaza by wyndham": "https://www.wyndhamhotels.com/ramada/west-hollywood-california/ramada-plaza-west-hollywood-hotel-and-suites/overview",
  "w los angeles - west beverly": "https://www.marriott.com/en-us/hotels/laxwb-w-los-angeles-west-beverly-hills/overview/",
  "plaza la reina": "https://www.plazalareina.com/",
  "kimpton hotel palomar": "https://www.ihg.com/kimptonhotels/hotels/us/en/hotel-palomar-beverly-hills-ca/laxww/hoteldetail",
  "holiday inn express west la": "https://www.ihg.com/holidayinnexpress/hotels/us/en/los-angeles/laxwl/hoteldetail",
  "royal palace westwood hotel": "https://www.royalpalacewestwood.com/",
  "the ritz-carlton, dtla": "https://www.ritzcarlton.com/en/hotels/laxlr-the-ritz-carlton-los-angeles/overview/",
  "the ritz-carlton, los angeles": "https://www.ritzcarlton.com/en/hotels/laxlr-the-ritz-carlton-los-angeles/overview/",
  "hotel figueroa": "https://www.hotelfigueroa.com/",
  "courtyard l.a. live": "https://www.marriott.com/en-us/hotels/laxcy-courtyard-los-angeles-l-a-live/overview/",
  "moxy downtown los angeles": "https://www.marriott.com/en-us/hotels/laxox-moxy-downtown-los-angeles/overview/",
  "freehand los angeles": "https://freehandhotels.com/los-angeles/",
  "shutters on the beach": "https://www.shuttersonthebeach.com/",
  "hotel erwin": "https://www.hotelerwin.com/",
  "hilton santa monica": "https://www.hilton.com/en/hotels/smopchh-hilton-santa-monica-hotel-and-suites/",
  "hampton inn & suites": "https://www.hilton.com/en/hotels/laxsmhx-hampton-suites-santa-monica/",
  "venice on the beach hotel": "https://www.veniceonthebeachhotel.com/",

  "norah": "https://www.norahrestaurant.com/",
  "dialog cafe": "https://www.dialogcafe.la/",
  "night + market weho": "https://www.nightmarketla.com/",
  "katsuya west hollywood": "https://www.katsuyarestaurant.com/",
  "rosaline": "https://www.rosalinela.com/",
  "gracias madre": "https://www.graciasmadre.com/",
  "cecconi’s west hollywood": "https://www.cecconiswesthollywood.com/",
  "cecconi's west hollywood": "https://www.cecconiswesthollywood.com/",
  "zinqué": "https://www.lezinque.com/",
  "zinque": "https://www.lezinque.com/",
  "the boiling crab": "https://theboilingcrab.com/",
  "in-n-out burger": "https://www.in-n-out.com/",
  "kazunori": "https://www.kazunorisushi.com/",
  "tsujita la artisan noodle": "https://www.tsujita.com/",
  "bella pita": "https://www.bellapita.com/",
  "cava": "https://cava.com/",
  "pomodoro trattoria": "https://www.pomodorotrattoria.com/",
  "le pain quotidien": "https://www.lepainquotidien.com/",
  "philippe the original": "https://www.philippes.com/",
  "eggslut": "https://www.eggslut.com/",
  "daikokuya ramen": "https://www.daikoku-ten.com/",
  "marugame monzo": "https://www.marugamemonzo.com/",
  "cabra la": "https://thehoxton.com/downtown-la/cabra/",
  "holbox": "https://www.holboxla.com/",
  "maccheroni republic": "https://www.maccheronirepublic.com/",
  "kendall’s brasserie": "https://www.patinagroup.com/kendalls-brasserie",
  "kendall's brasserie": "https://www.patinagroup.com/kendalls-brasserie",
  "hiho cheeseburger": "https://www.hiho.la/",
  "blue plate taco": "https://www.blueplatetaco.com/",
  "hae jang chon": "https://www.haejangchon.com/",
  "tatsu ramen": "https://www.tatsuramen.com/",
  "socalo": "https://www.socalo.com/",
  "cha cha chicken": "https://www.chachachicken.com/",
  "forma restaurant & cheese bar": "https://www.formarestaurant.com/",
  "pasjoli": "https://www.pasjoli.com/",

  "hollywood bowl orchestra night": "https://www.hollywoodbowl.com/",
  "hollywood bowl jazz night": "https://www.hollywoodbowl.com/",
  "hollywood bowl guest artist night": "https://www.hollywoodbowl.com/",
  "hollywood improv stand-up show": "https://improv.com/hollywood/",
  "hollywood improv late show": "https://improv.com/hollywood/",
  "cinespia outdoor movie": "https://cinespia.org/",
  "the echo live indie show": "https://www.theecho.com/",
  "the echo dj night": "https://www.theecho.com/",
  "the comedy store stand-up": "https://thecomedystore.com/",
  "comedy store late night": "https://thecomedystore.com/",
  "troubadour live concert": "https://troubadour.com/",
  "troubadour indie night": "https://troubadour.com/",
  "the roxy theatre live show": "https://www.theroxy.com/",
  "laugh factory comedy night": "https://www.laughfactory.com/hollywood",

  "santa monica": "https://www.santamonica.com/",
  "venice beach": "https://www.visitveniceca.com/",
  "malibu (zuma/point dume)": "https://beaches.lacounty.gov/zuma-beach/",
  "laguna beach": "https://www.visitlagunabeach.com/",
  "huntington beach": "https://www.surfcityusa.com/",
  "hollywood sign": "https://www.hollywoodsign.org/",
  "walk of fame": "https://walkoffame.com/",
  "griffith observatory": "https://griffithobservatory.org/",
  "downtown la": "https://www.discoverlosangeles.com/things-to-do/downtown-los-angeles",
  "universal studios hollywood": "https://www.universalstudioshollywood.com/",
  "disneyland anaheim": "https://disneyland.disney.go.com/",
  "warner bros studio tour": "https://www.wbstudiotour.com/",
  "paramount studios": "https://www.paramountstudiotour.com/",
  "getty center": "https://www.getty.edu/visit/center/",
  "lacma": "https://www.lacma.org/",
  "the broad": "https://www.thebroad.org/",
  "getty villa": "https://www.getty.edu/visit/villa/",
  "rodeo drive": "https://rodeodrive-bh.com/",
  "the grove": "https://thegrovela.com/",
  "abbot kinney blvd": "https://www.abbotkinneyblvd.com/",
  "melrose avenue": "https://www.discoverlosangeles.com/things-to-do/the-guide-to-melrose-avenue",
  "runyon canyon": "https://www.laparks.org/park/runyon-canyon",
  "griffith park trails": "https://www.laparks.org/griffithpark/",
  "el matador beach": "https://beaches.lacounty.gov/el-matador-beach/",
  "topanga canyon": "https://www.parks.ca.gov/?page_id=629",

  "game on! science, sports & play": "https://californiasciencecenter.org/",
  "fútbol is life: animated sportraits by lyndon j. barrois, sr.": "https://www.lacma.org/",
  "lights, camera, goal!!!: community free day at the academy museum": "https://www.academymuseum.org/",
  "ye olde king's head": "https://www.yeoldekingshead.com/",
  "tom's watch bar": "https://tomswatchbar.com/",
  "guelaguetza": "https://www.ilovemole.com/",
  "wirtshaus": "https://www.wirtshausla.com/",
  "la riot squad (lars)": "https://lariotsquad.com/",
  "the 3253": "https://the3252.net/",
  "los angeles angels vs tampa bay rays": "https://www.mlb.com/angels",
  "los angeles angels vs baltimore orioles": "https://www.mlb.com/angels",
  "los angeles angels vs athletics": "https://www.mlb.com/angels",
  "los angeles dodgers vs tampa bay rays": "https://www.mlb.com/dodgers",
  "los angeles dodgers vs baltimore orioles": "https://www.mlb.com/dodgers",
  "los angeles dodgers vs san diego padres": "https://www.mlb.com/dodgers",
  "los angeles sparks vs minnesota lynx": "https://sparks.wnba.com/",
  "los angeles sparks vs new york liberty": "https://sparks.wnba.com/",
  "los angeles sparks vs seattle storm": "https://sparks.wnba.com/",
  "los angeles sparks vs indiana fever": "https://sparks.wnba.com/",
  "los angeles sparks vs chicago sky": "https://sparks.wnba.com/",
  "possibly perfect stakes (live racing day)": "https://www.santaanita.com/",
  "daytona stakes + summertime oaks (live racing day)": "https://www.santaanita.com/",
  "san juan capistrano stakes (live racing day)": "https://www.santaanita.com/",
  "socal pro series: los angeles": "https://socalproseries.com/",
  "socal pro series: claremont": "https://socalproseries.com/",
};

const FALLBACK_IMAGES = {
  hotels: "images/hotel.jpg",
  restaurants: "images/Resturant.jpg",
  events: "images/fanevent.jpg",
  shows: "images/shows.jpg",
  attractions: "images/attraction.jpg",
};

function keyFor(value = "") {
  return value.trim().toLowerCase();
}

function screenshotFor(url) {
  if (!url) return "";
  return `https://image.thum.io/get/width/700/crop/440/noanimate/${encodeURIComponent(url)}`;
}

export function mediaForPlace(name, category, officialUrl = "") {
  const url = officialUrl || PLACE_URLS[keyFor(name)] || "";
  const fallbackImage = FALLBACK_IMAGES[category] || "images/LA5.jpg";
  return {
    officialUrl: url,
    fallbackImage,
    imageUrl: url ? screenshotFor(url) : fallbackImage,
  };
}
